export const ui = {
  app: {
    sheetControls: 'Sheet size controls', moreLinks: 'More information links', setSheetHalf: 'Set controls sheet to half height', expandSheet: 'Expand controls sheet', collapseSheet: 'Collapse controls sheet', switchToLight: 'Switch to light mode', switchToDark: 'Switch to dark mode', load: 'Load', startHere: 'Start here', animate: 'Animate', inspect: 'Inspect', sharedPreview: 'Shared Preview', shareLoadFailed: 'Share load failed', share: 'Share', webmClip: 'WebM Clip', recording: 'Recording...', exportWebm: 'Export WebM', shareSetup: 'Share Setup', watermarkTextures: 'Watermark textures', watermarkHint: 'Export texture pages as WebP and apply a static watermark.', clipCurrentAnimation: 'Clip to current animation', defaults: 'Defaults', sharing: 'Sharing...', createShareLink: 'Create Share Link', shareHistory: 'Share History', open: 'Open', copy: 'Copy', loadAsset: 'Load a Spine asset', useLoadPanel: 'Use the Load panel', mobileControls: 'Mobile controls', openShareConfirmation: 'Open share confirmation', shareConfirmation: 'Share Confirmation', createPreviewLink: 'Create 24-hour preview link', closeShareConfirmation: 'Close share confirmation', filesToUpload: 'Files to upload', shareSettings: 'Share settings', expires: 'Expires', watermark: 'Watermark', animationContent: 'Animation content', defaultPreview: 'Default preview', cancel: 'Cancel', creating: 'Creating...', about: 'About', closeInfo: 'Close info dialog', skeletonJson: 'Skeleton JSON', atlas: 'Atlas', texture: 'Texture', file: 'File', revoked: 'Revoked', expired: 'Expired', active: 'Active', revoke: 'Revoke', copyShareLink: 'Copy share link', firstAvailableAnimation: 'First available animation', setupPoseSkin: 'Setup pose skin', failedSharedAssets: 'Failed to load shared assets', unnamedEvent: 'Unnamed event', failedCreateShareLink: 'Failed to create share link', failedExportWebm: 'Failed to export WebM', shareLinkRevoked: 'Share link revoked', failedRevokeShareLink: 'Failed to revoke share link'
  },
  canvas: { loading: 'Loading...', failedToLoad: 'Failed to load' },
  load: {
    selectFiles: 'Select Spine files', selectFolder: 'Select a Spine asset folder', selectDriveFiles: 'Select Spine files from Google Drive', picking: 'Picking...', drive: 'Drive', loadedFiles: 'Loaded Files', hideList: 'Hide list', showList: 'Show list', analyzingGroups: 'Analyzing file groups...', folderHint: 'Use Folder to load a whole Spine asset directory without Ctrl multi-select.', detectedSets: 'Detected Sets', ready: 'Ready', needsFix: 'Needs Fix', noAtlas: 'No atlas', addMissingFiles: 'Add Missing Files', loadAnimation: 'Load Animation', failedDrive: 'Failed to load files from Google Drive', directoryUnsupported: 'Directory iteration is not supported in this browser', noSupportedFolderFiles: 'No supported Spine files found in the selected folder', failedFolderRead: 'Failed to read the selected folder', noSupportedFiles: 'No supported Spine files were selected', failedAnalysis: 'Failed to analyze selected files'
  },
  control: {
    animationTracks: 'Animation Tracks', add: 'Add', none: 'None', loop: 'Loop', mix: 'Mix', overview: 'Overview', skin: 'Skin', default: 'Default', drawCalls: 'Draw Calls', eventMarkers: 'Event Markers', display: 'Display', xyAxes: 'XY Axes', premultipliedAlpha: 'Premultiplied Alpha', filtering: 'Filtering', debug: 'Debug', detected: 'Detected', runtime: 'Runtime', fallback: 'Fallback', debugOptions: { showBones: 'Bones', showRegions: 'Regions', showBounds: 'Bounds', showPaths: 'Paths', showPoints: 'Points', showClipping: 'Clipping', showMeshHull: 'Mesh hull', showMeshTriangles: 'Triangles' }
  },
  playback: { fallbackTitle: 'Playback', expand: 'Expand playback controls', collapse: 'Collapse playback controls', track: 'Track', stop: 'Stop', stopAria: 'Stop playback and return to start', pause: 'Pause', play: 'Play', pauseAria: 'Pause playback', playAria: 'Play animation', speedAria: 'Playback speed', unnamedEvent: 'Unnamed event' },
  tree: { title: 'Skeleton Tree', actions: 'Skeleton tree actions', expandAll: 'Expand all', expandAllAria: 'Expand all skeleton nodes', collapseAll: 'Collapse all', collapseAllAria: 'Collapse all skeleton nodes', empty: 'Load a skeleton to inspect its hierarchy.', expand: 'Expand', collapse: 'Collapse', noAttachment: 'no attachment' }
} as const
